### ISSUE TITLE
 Add examples for VM instances

### ISSUE THREAD

**Issue by scraly** [ovh/pulumi-ovh#64]
It will be useful to add examples for VM Instances in:

- Python
- Go/Golang
- Javascript/Typescript
- C#/Dotnet

Where?
https://github.com/ovh/pulumi-ovh/tree/main/examples

**Comment by ugal1silbo** [comment]
Completed? 🤯

**Comment by scraly** [comment]
Few months ago it was not possible to deploy Public CLoud Instances through Terraform and Pulumi. So the issue was "closed".
Now it is possible so examples can be write.

**Comment by ugal1silbo** [comment]
Thanks for the clarification 👍
